### ISSUE TITLE
Add support for minikube

### ISSUE THREAD

**Issue by badrange** [wunderio/silta#53]
Now that silta already supports three different kubernetes vendors I wonder if it would make sense to add a fourth: minikube?

As a developer working on a silta-based project I've sometimes had a need to develop new features to silta, or diagnose issues in the cluster - which is not possible at the moment since I don't have the necessary access to the cluster.

Would this be an idea to consider?

**Comment by Jancis** [comment]
Definitely, minikube sounds like a good option. So far it is tested in [k3s](https://k3s.io/) due to low overhead and [microk8s](https://microk8s.io/) due to canonical's support, but could also try minikube. So far we've avoided minikube due to resource  overhead in virtualization, but we might give it a shot and provide short instruction to run it. 

Using microk8s for automated compatibility tests is on the development board, might as well switch it out for minikube if it works well enough.

ETA: unknown

**Comment by badrange** [comment]
I wasn't aware of k3s and microk8s. The reason for why I asked about minikube was actually more that I would like to be able to run a local cluster for our project in the few cases where I've wanted to create prs to silta or charts. Should I rename the issue to: "Document how to run silta locally" :-)

**Comment by Jancis** [comment]
There is no such functionality yet. Definitely something to consider, but not available at the moment and no eta either.
I'll close the ticket now so these don't pile up.
